print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/McDirty/speed_run/ScarecrowTrufflePro/Assets/sources/Vine_Temp.mb"`)
{		
	file -o "/Users/McDirty/speed_run/ScarecrowTrufflePro/Assets/sources/Vine_Temp.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/McDirty/speed_run/ScarecrowTrufflePro/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/McDirty/speed_run/ScarecrowTrufflePro/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/McDirty/speed_run/ScarecrowTrufflePro/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
